# https://github.com/toml-lang/toml         https://github.com/avakar/pytoml
#
# This file contains the config by default
#
title = "immotrack-config-defaults"

[servers]
# RethinkDB server wont be overriden as custom config will be stored in rdb
"rdb.ip"      = "127.0.0.1"
"rdb.port"    = 28015
"rdb.base"    = "immotrack"
"rdb.cfg.tbl" = "config"
"rdb.tables"  = ["config", "villesfr", "immoanno", "immoanno_users", "immoimg", "logs"]
# InfluxDB and other servers will be overriden by custom config with specific access and password
"idb.ip"     = "127.0.0.1"
"idb.port"   = 8086
"idb.login"  = "john"
"idb.pwd"    = "doe"
"idb.kpi.db" = "test"
splashserver = "127.0.0.1"

[websrv]
"network.port"  = 13354
[websrv.users]
"" = ""

["fetcher"]
daily_hour = "17:45"
# item exclu si une de ces pattern est trouvee dans le nom de la ville ou dans le codepostal
localites_exclure = []
